
server:
  port: 8082
  servlet:
    context-path: /pagamento
  
spring:
  application:
    name: crud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#     dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource: 
    url: jdbc:mysql://localhost:3306/microservico-pagamento?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    
          
